import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import styles from "@/components/Footer/Footer.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Immigration Lawyer",
  description: "Generated by create next app",
  icons: {
    icon: "/iconAKLawyer.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapperFT}>
          <Header />
          <main className={styles.mainFT}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
