import type { Metadata } from "next";
import { Lora, Mulish, Roboto_Condensed } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import styles from "@/components/Footer/Footer.module.scss";

const lora = Lora({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-lora",
  display: "swap",
});

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-mulish",
  display: "swap",
});
const robotoCond = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "500"],
  style: ["normal", "italic"],
  variable: "--font-robotoCond",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Immigration Lawyer",
  description: "Generated by create next app",
  icons: {
    icon: "/iconAKLawyer.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${mulish.variable} ${robotoCond.variable}`}
    >
      <body>
        <div className={styles.wrapperFT}>
          <Header />

          <main className={styles.mainFT}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
