import type { Metadata } from "next";
import { Lora, Mulish, Roboto_Condensed } from "next/font/google";
import { NextIntlClientProvider, useMessages } from "next-intl";
import "./globals.css";

import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";

const lora = Lora({
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: "--font-lora",
  display: "swap",
});

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-mulish",
  display: "swap",
});
const robotoCond = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "500"],
  style: ["normal", "italic"],
  variable: "--font-robotoCond",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Immigration Lawyer",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();
  return (
    <html
      lang={locale}
      className={`${lora.variable} ${mulish.variable} ${robotoCond.variable}`}
    >
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body>
          <div className="flex flex-col min-h-[100%]">
            <Header />

            <main className="flex-[1_0_auto]">{children}</main>
            <Footer />
          </div>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
